# Generated by Django 2.1.7 on 2019-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
