# Generated by Django 2.1.7 on 2019-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_session_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='full',
            field=models.BooleanField(default=False, verbose_name='Complet'),
        ),
    ]
