# Generated by Django 2.1.7 on 2019-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_session_availabe_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='places_max',
        ),
        migrations.AddField(
            model_name='session',
            name='seat_max',
            field=models.IntegerField(null=True, verbose_name='Nombre de places'),
        ),
    ]
