# Generated by Django 2.1.7 on 2019-03-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20190331_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='seat_max',
            new_name='seats_max',
        ),
    ]
