# Generated by Django 2.1.7 on 2019-05-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20190331_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Category', verbose_name='Catégorie'),
        ),
    ]
