# Generated by Django 2.1.7 on 2019-05-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190509_0125'),
        ('training', '0007_auto_20190509_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='teacher',
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(default=2, limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Formateur'),
        ),
    ]
