# Generated by Django 2.1.7 on 2019-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20190512_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image_training',
            field=models.ImageField(blank=True, upload_to='training', verbose_name='Image Formation'),
        ),
    ]
