# Generated by Django 2.1.7 on 2019-03-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20190313_1532'),
        ('training', '0003_auto_20190315_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Statut')),
                ('date_of_registration', models.DateTimeField(auto_now=True, verbose_name="Date d' inscription")),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session', verbose_name='Session')),
            ],
        ),
    ]
