# Generated by Django 2.1.7 on 2019-03-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190324_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'verbose_name': 'Inscription à une session', 'verbose_name_plural': 'Inscription aux sessions'},
        ),
    ]
