# Generated by Django 2.1.7 on 2019-05-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190331_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsession',
            name='date_of_registration',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Date d' inscription"),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En Attente'), (2, 'Confirmer'), (3, 'Annuler')], default=1, verbose_name='Statut'),
        ),
    ]
