# Generated by Django 2.1.7 on 2019-05-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20190509_0125'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='formation',
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.Session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date de facturation'),
        ),
    ]
