# Generated by Django 2.1.7 on 2019-05-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190509_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session', verbose_name='Session'),
        ),
    ]
