# Generated by Django 2.1.7 on 2019-06-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_invoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.RegistrationSession', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile', verbose_name='Etudiant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.Session', verbose_name='Session'),
        ),
    ]
