# Generated by Django 2.1.7 on 2019-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.FloatField(verbose_name='Prix'),
        ),
    ]
