# Generated by Django 2.1.7 on 2019-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20190606_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix'),
        ),
    ]
