# Generated by Django 2.1.7 on 2019-03-13 14:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(max_length=150, verbose_name='Diplome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Télephone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place_of_birth',
            field=models.CharField(max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Rue'),
        ),
    ]
