# Generated by Django 2.1.7 on 2019-05-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190313_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Etudiant'), (2, 'Formateur'), (3, 'Administrateur')], default=1, verbose_name='Type'),
        ),
    ]
