# Generated by Django 2.1.7 on 2019-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190225_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
