# Generated by Django 2.1.7 on 2019-05-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_profile',
        ),
    ]
