# Generated by Django 2.1.7 on 2019-05-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0008_auto_20190512_1421'),
        ('account', '0003_auto_20190509_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attandence', models.DateField(verbose_name='Date de présence')),
                ('attendance_choices', models.PositiveSmallIntegerField(choices=[(1, 'Présent'), (2, 'Absent'), (3, 'Absence justifiée'), (3, 'Absence non justifiée')], default=1, verbose_name='Présence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session')),
                ('student', models.ForeignKey(default=1, limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Etudiant')),
            ],
        ),
    ]
