# Generated by Django 2.1.7 on 2019-05-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='date_of_attandence',
            new_name='date_of_attendance',
        ),
    ]
