# Generated by Django 2.1.7 on 2019-05-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20190512_1421'),
        ('account', '0003_auto_20190509_0125'),
        ('teacher', '0002_auto_20190514_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.PositiveSmallIntegerField(default=0, max_length=100)),
                ('date_of_assessment', models.DateField(verbose_name="Date de l'évaluation")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session')),
                ('student', models.ForeignKey(default=1, limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Etudiant')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_choices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Présent'), (2, 'Absent'), (3, 'Absence justifiée'), (4, 'Absence non justifiée')], default=2, verbose_name='Présence'),
        ),
    ]
