# Generated by Django 2.1.7 on 2019-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190522_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Evaluation'),
        ),
    ]
